import type { AttendanceRecord } from "@/features/attendance/types";
import type { Learner } from "@/features/learners/types";
import type { PaymentRecord } from "@/features/payments/types";
import type { ParentSubmissionRecord as ParentSubmission } from "@/features/parents/types";
import type { RecentActivity } from "@/types/activity";

export const demoLearners: Learner[] = [
  {
    id: "learner-1",
    firstName: "Zara",
    lastName: "Dlamini",
    className: "Grade 3A",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Piano",
    parentName: "Thandi Dlamini",
    parentPhone: "0845550103",
    parentEmail: "thandi.dlamini@example.com",
    paymentStatus: "paid",
    learnerStatus: "active",
    notes: "Prefers Monday afternoon lessons.",
    createdAt: new Date("2026-05-01T08:00:00+02:00").toISOString(),
    updatedAt: new Date("2026-05-24T10:30:00+02:00").toISOString(),
  },
  {
    id: "learner-2",
    firstName: "Liam",
    lastName: "Smith",
    className: "Grade 4B",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Guitar",
    parentName: "Sarah Smith",
    parentPhone: "0835550102",
    parentEmail: "sarah.smith@example.com",
    paymentStatus: "partial",
    learnerStatus: "active",
    notes: "Needs invoice follow-up before month end.",
    createdAt: new Date("2026-05-03T09:15:00+02:00").toISOString(),
    updatedAt: new Date("2026-05-25T12:00:00+02:00").toISOString(),
  },
  {
    id: "learner-3",
    firstName: "Amahle",
    lastName: "Nkosi",
    className: "Grade 2C",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Drums",
    parentName: "Bongani Nkosi",
    parentPhone: "0825550101",
    parentEmail: "bongani.nkosi@example.com",
    paymentStatus: "unpaid",
    learnerStatus: "pending",
    notes: "Trial learner awaiting placement confirmation.",
    createdAt: new Date("2026-05-08T14:00:00+02:00").toISOString(),
    updatedAt: new Date("2026-05-26T09:45:00+02:00").toISOString(),
  },
  {
    id: "learner-4",
    firstName: "Noah",
    lastName: "van der Merwe",
    className: "Grade 5A",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Vocals",
    parentName: "Johan van der Merwe",
    parentPhone: "0715550104",
    parentEmail: "johan@example.com",
    paymentStatus: "overdue",
    learnerStatus: "active",
    notes: "Do not schedule extra sessions until payment is resolved.",
    createdAt: new Date("2026-04-20T11:30:00+02:00").toISOString(),
    updatedAt: new Date("2026-05-27T16:20:00+02:00").toISOString(),
  },
  {
    id: "learner-5",
    firstName: "Chloe",
    lastName: "Naidoo",
    className: "Grade 1B",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Violin",
    parentName: "Priya Naidoo",
    parentPhone: "0835550105",
    paymentStatus: "paid",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-6",
    firstName: "Jayden",
    lastName: "Peters",
    className: "Grade 6C",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Trumpet",
    parentName: "Michael Peters",
    parentPhone: "0815550106",
    paymentStatus: "paid",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-7",
    firstName: "Mia",
    lastName: "Johnson",
    className: "Grade 7A",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Flute",
    parentName: "David Johnson",
    parentPhone: "0825550107",
    paymentStatus: "partial",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-8",
    firstName: "Ethan",
    lastName: "Govender",
    className: "Grade 4C",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Piano",
    parentName: "Anil Govender",
    parentPhone: "0845550108",
    paymentStatus: "unpaid",
    learnerStatus: "inactive",
    notes: "Taking a break this term.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-9",
    firstName: "Sophie",
    lastName: "Botha",
    className: "Grade 3B",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Recorder",
    parentName: "Riana Botha",
    parentPhone: "0715550109",
    paymentStatus: "paid",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-10",
    firstName: "Lucas",
    lastName: "Sithole",
    className: "Grade 5B",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Guitar",
    parentName: "Mbali Sithole",
    parentPhone: "0835550110",
    paymentStatus: "overdue",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-11",
    firstName: "Isabella",
    lastName: "Ndlovu",
    className: "Grade 2A",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Choir",
    parentName: "Nomsa Ndlovu",
    parentPhone: "0825550111",
    paymentStatus: "paid",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-12",
    firstName: "Mason",
    lastName: "Pillay",
    className: "Grade 6A",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Drums",
    parentName: "Raj Pillay",
    parentPhone: "0815550112",
    paymentStatus: "partial",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-13",
    firstName: "Aria",
    lastName: "Fourie",
    className: "Grade 1A",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Music Theory",
    parentName: "Kobus Fourie",
    parentPhone: "0845550113",
    paymentStatus: "paid",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-14",
    firstName: "Leo",
    lastName: "Jacobs",
    className: "Grade 7B",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Trombone",
    parentName: "Nadia Jacobs",
    parentPhone: "0825550114",
    paymentStatus: "paid",
    learnerStatus: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "learner-15",
    firstName: "Grace",
    lastName: "Mokoena",
    className: "Grade 3C",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Vocals",
    parentName: "Lindiwe Mokoena",
    parentPhone: "0715550115",
    paymentStatus: "unpaid",
    learnerStatus: "pending",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
] as unknown as Learner[];

export const demoAttendance: AttendanceRecord[] = [
  {
    id: "attendance-1",
    learnerId: "learner-1",
    learnerName: "Zara Dlamini",
    className: "Grade 3A",
    programme: "TKM Music Academy",
    date: new Date().toISOString().split("T")[0],
    status: "present",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "attendance-2",
    learnerId: "learner-2",
    learnerName: "Liam Smith",
    className: "Grade 4B",
    programme: "TKM Music Academy",
    date: new Date().toISOString().split("T")[0],
    status: "late",
    notes: "Arrived 10 minutes late.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "attendance-3",
    learnerId: "learner-3",
    learnerName: "Amahle Nkosi",
    className: "Grade 2C",
    programme: "TKM Music Academy",
    date: new Date().toISOString().split("T")[0],
    status: "excused",
    notes: "Parent notified school event clash.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "attendance-4",
    learnerId: "learner-4",
    learnerName: "Noah van der Merwe",
    className: "Grade 5A",
    programme: "TKM Music Academy",
    date: new Date().toISOString().split("T")[0],
    status: "absent",
    notes: "Follow up required.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
] as unknown as AttendanceRecord[];

export const demoPayments: PaymentRecord[] = [
  {
    id: "payment-1",
    learnerId: "learner-1",
    learnerName: "Zara Dlamini",
    month: "2026-05",
    expectedAmount: 750,
    paidAmount: 750,
    balance: 0,
    status: "paid",
    paymentDate: "2026-05-08",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "payment-2",
    learnerId: "learner-2",
    learnerName: "Liam Smith",
    month: "2026-05",
    expectedAmount: 850,
    paidAmount: 400,
    balance: 450,
    status: "partial",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "payment-3",
    learnerId: "learner-3",
    learnerName: "Amahle Nkosi",
    month: "2026-05",
    expectedAmount: 650,
    paidAmount: 0,
    balance: 650,
    status: "unpaid",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "payment-4",
    learnerId: "learner-4",
    learnerName: "Noah van der Merwe",
    month: "2026-05",
    expectedAmount: 900,
    paidAmount: 0,
    balance: 900,
    status: "overdue",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
] as unknown as PaymentRecord[];

export const demoParentSubmissions: ParentSubmission[] = [
  {
    id: "submission-1",
    learnerFirstName: "Sipho",
    learnerLastName: "Mthembu",
    className: "Grade 4A",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Guitar",
    parentName: "Themba Mthembu",
    parentPhone: "0831234567",
    parentEmail: "themba@example.com",
    status: "new",
    message: "We would like to start next month if possible.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "submission-2",
    learnerFirstName: "Emma",
    learnerLastName: "Viljoen",
    className: "Grade 1B",
    programme: "TKM Music Academy",
    instrumentOrActivity: "Piano",
    parentName: "Susan Viljoen",
    parentPhone: "0829876543",
    status: "reviewed",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
] as unknown as ParentSubmission[];

export const demoRecentActivity: RecentActivity[] = [
  {
    id: "activity-1",
    type: "learner_added",
    title: "New Learner Added",
    description: "Grace Mokoena was added to TKM Music Academy.",
    timestamp: new Date().toISOString(),
  },
  {
    id: "activity-2",
    type: "attendance_marked",
    title: "Attendance Recorded",
    description: "Marked Liam Smith as late for Guitar.",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
  },
  {
    id: "activity-3",
    type: "parent_form_submitted",
    title: "New Parent Submission",
    description: "Themba Mthembu submitted an application for Sipho.",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
  }
] as unknown as RecentActivity[];

export const emptyLearners = demoLearners;
export const emptyAttendance = demoAttendance;
export const emptyPayments = demoPayments;

export const demoData = {
  learners: demoLearners,
  attendance: demoAttendance,
  payments: demoPayments,
  parentSubmissions: demoParentSubmissions,
  recentActivity: demoRecentActivity,
};
